/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PascalitoStandaloneSetup extends PascalitoStandaloneSetupGenerated {

	def static void doSetup() {
		new PascalitoStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
